#!/usr/bin/env ruby

# J clone helper (cl1)
# Authour: lumiknit (aasr4r4@gmail.com)
# Version: 0.0.1 (230307)


$repos = ENV['J_REPOS']

def clone url
  regex = /^((http|https|git):\/\/)?([A-Za-z0-9.-]+)\/([A-Za-z0-9._-]+)\/([A-Za-z0-9._-]+?)(.git)?$/
  data = regex.match url
  if data == nil
    puts "[ERROR] Wrong URL: #{url}"
    return
  end
  d0 = data[3]
  d1 = data[4]
  d2 = data[5]
  dest = "#{$repos}/#{d0}/#{d1}/#{d2}"
  system "mkdir -p #{dest}"
  system "git clone #{url} #{dest}"
end

def apply arg
  clone arg
end

if ARGV.length == 0
  puts "Usage: clone <repo>"
  exit 1
end

ARGV.each do |arg|
  apply arg
end